schema = 3

[mod]
  [mod."github.com/aws/aws-sdk-go"]
    version = "v1.44.195"
    hash = "sha256-txBlCeKTZCbIXfpyX0IGv8WcT4UtnmwWiTT5G4Y2LCw="
  [mod."github.com/jmespath/go-jmespath"]
    version = "v0.4.0"
    hash = "sha256-xpT9g2qIXmPq7eeHUXHiDqJeQoHCudh44G/KCSFbcuo="
  [mod."github.com/kr/pretty"]
    version = "v0.1.0"
    hash = "sha256-Fx+TaNrxW0VfzonT2jnd5MU09RRz7GJZkqAtJR6/pKI="
  [mod."github.com/sirupsen/logrus"]
    version = "v1.9.0"
    hash = "sha256-xOwGFsYGIxNiurS8Zue8mhlFK/G7U1LVFFrv4vcr1GM="
  [mod."github.com/stretchr/testify"]
    version = "v1.7.0"
    hash = "sha256-t1I9uCrn9vSUu/z5IZuNyGShmbOcJ6UGc2f75ZBrHzE="
  [mod."golang.org/x/crypto"]
    version = "v0.0.0-20210921155107-089bfa567519"
    hash = "sha256-62Qtoqu7AxoxpZFd+75qXC0naixAct3rWsJd0nSgMCU="
  [mod."golang.org/x/sys"]
    version = "v0.5.0"
    hash = "sha256-0LTr3KeJ1OMQAwYUQo1513dXJtQAJn5Dq8sFkc8ps1U="
  [mod."gopkg.in/check.v1"]
    version = "v1.0.0-20180628173108-788fd7840127"
    hash = "sha256-KsRJNTprd1UijnJusbHwQGM7Bdm45Jt/QL+cIUGNa2w="
  [mod."gopkg.in/yaml.v2"]
    version = "v2.4.0"
    hash = "sha256-uVEGglIedjOIGZzHW4YwN1VoRSTK8o0eGZqzd+TNdd0="
